using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Atmos.BUI;
using Content.Shared._NF.Bank;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasPurchaseMenu : FancyWindow
{
    public Action? RefreshRequested;
    public Action? PurchaseRequested;
    public Action<int>? GasSelected;
    public Action<float>? AmountChanged;

    private bool _updatingState;

    public GasPurchaseMenu()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => RefreshRequested?.Invoke();
        PurchaseButton.OnPressed += _ => PurchaseRequested?.Invoke();
        GasSelector.OnItemSelected += OnGasItemSelected;
        AmountInput.OnTextChanged += OnAmountTextChanged;
    }

    public void SetState(GasPurchaseConsoleBoundUserInterfaceState state)
    {
        _updatingState = true;

        GasSelector.Clear();
        foreach (var gasId in state.AvailableGasIds)
        {
            var gas = (Gas) gasId;
            var gasName = GetGasDisplayName(gas, gasId);

            GasSelector.AddItem(gasName, gasId);
        }

        if (state.AvailableGasIds.Length > 0)
        {
            GasSelector.Disabled = false;
            GasSelector.SelectId(state.SelectedGasId);
        }
        else
        {
            GasSelector.Disabled = true;
        }

        AmountInput.Text = state.Moles.ToString("0.##", CultureInfo.InvariantCulture);
        PriceLabel.Text = state.Price > 0
            ? BankSystemExtensions.ToSpesoString(state.Price)
            : Loc.GetString("gas-purchase-menu-no-value");
        LinkedPointsLabel.Text = state.LinkedPoints.ToString(CultureInfo.InvariantCulture);
        PurchaseButton.Disabled = !state.CanPurchase;

        _updatingState = false;
    }

    private void OnGasItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        args.Button.SelectId(args.Id);
        if (_updatingState)
            return;

        GasSelected?.Invoke(args.Id);
    }

    private void OnAmountTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (_updatingState)
            return;

        var trimmed = args.Text.Trim();
        if (!float.TryParse(trimmed, NumberStyles.Float, CultureInfo.InvariantCulture, out var moles))
            moles = 0f;

        AmountChanged?.Invoke(moles);
    }

    private static string GetGasDisplayName(Gas gas, int gasId)
    {
        var key = gas switch
        {
            Gas.Oxygen => "gases-oxygen",
            Gas.Nitrogen => "gases-nitrogen",
            Gas.CarbonDioxide => "gases-co2",
            Gas.Plasma => "gases-plasma",
            Gas.Tritium => "gases-tritium",
            Gas.WaterVapor => "gases-water-vapor",
            Gas.Ammonia => "gases-ammonia",
            Gas.NitrousOxide => "gases-n2o",
            Gas.Frezon => "gases-frezon",
            Gas.BZ => "gases-bz",
            Gas.Healium => "gases-healium",
            Gas.Pluoxium => "gases-pluoxium",
            Gas.Nitrium => "gases-nitrium",
            _ => null,
        };

        return key != null
            ? Loc.GetString(key)
            : Loc.GetString("gas-fallback", ("number", gasId));
    }
}